import Head from "next/head";
import { FullScreenCanvas, PositionedGroup } from "@bsmnt/webgl";
import { useRef } from "react";

export default function Home() {
  const shadowRef = useRef<HTMLDivElement>(null);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FullScreenCanvas>
        <ambientLight intensity={0.25} />
      </FullScreenCanvas>

      <FullScreenCanvas.InScroll>
        <PositionedGroup shadowRef={shadowRef}>
          <mesh>
            <boxGeometry />
            <meshStandardMaterial color="#ff0000" />
          </mesh>
        </PositionedGroup>
      </FullScreenCanvas.InScroll>

      <div
        ref={shadowRef}
        style={{
          width: "100px",
          height: "100px",
          position: "relative",
          zIndex: 1,
          border: "1px solid blue",
        }}
      />
    </div>
  );
}
